ALTER TABLE PRODUCTS DROP FOREIGN KEY FK_PRODUCTS_Company_ID
ALTER TABLE combo_item DROP FOREIGN KEY FK_combo_item_product_id
ALTER TABLE combo_item DROP FOREIGN KEY FK_combo_item_combo_id
DROP TABLE COMBOS
DROP TABLE COMPANY
DROP TABLE CUSTOMER
DROP TABLE MARKETINGTREE
DROP TABLE MEMBERS
DROP TABLE PRODUCTS
DROP TABLE combo_item
